export const STATUS = {
  OPERATIONAL: "OPERATIONAL",
  UNDER_MAINTENANCE: "UNDER_MAINTENANCE",
  OUT_OF_SERVICE: "OUT_OF_SERVICE",
};

export const CATEGORY = {
  AGRICULTURAL_MACHINERY: "AGRICULTURAL_MACHINERY",
  AGRICULTURAL_EQUIPMENT: "AGRICULTURAL_EQUIPMENT",
  PROCESSING_MACHINERY: "PROCESSING_MACHINERY",
};

export const STAGE = {
  CULTIVATION: "CULTIVATION",
  HARVEST: "HARVEST",
  PROCESSING: "PROCESSING",
  DRYING: "DRYING",
};