package com.sustainablefarm.service.impl;

import com.sustainablefarm.model.HarvestEvent;
import com.sustainablefarm.model.HarvestEvent.MangoVariety;
import com.sustainablefarm.model.HarvestEvent.QualityGrade;
import com.sustainablefarm.repository.HarvestEventRepository;
import com.sustainablefarm.service.HarvestEventService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

/**
 * Service Implementation for HarvestEvent Entity
 * Harvest data from Plants workstream - Integration Entity
 * 
 * Business Rules:
 * - Batch ID generated by Plants system
 * - One harvest event creates exactly one batch
 * - Plants workstream integration
 * 
 * @author Abdoul Ben Fatao SANON
 * @version 1.0.0
 */
@Service
@Transactional
public class HarvestEventServiceImpl implements HarvestEventService {

    private final HarvestEventRepository harvestEventRepository;

    @Autowired
    public HarvestEventServiceImpl(HarvestEventRepository harvestEventRepository) {
        this.harvestEventRepository = harvestEventRepository;
    }

    @Override
    public HarvestEvent createHarvestEvent(HarvestEvent harvestEvent) {
        // Business Rule: Validate batch ID uniqueness
        if (harvestEvent.getBatchId() != null && batchIdExists(harvestEvent.getBatchId())) {
            throw new IllegalArgumentException("Batch ID already exists: " + harvestEvent.getBatchId());
        }
        
        return harvestEventRepository.save(harvestEvent);
    }

    @Override
    public HarvestEvent updateHarvestEvent(String harvestId, HarvestEvent harvestEvent) {
        HarvestEvent existingEvent = getHarvestEventById(harvestId);
        
        // Update fields
        existingEvent.setBatchId(harvestEvent.getBatchId());
        existingEvent.setHarvestDate(harvestEvent.getHarvestDate());
        existingEvent.setHarvestTime(harvestEvent.getHarvestTime());
        existingEvent.setMangoVariety(harvestEvent.getMangoVariety());
        existingEvent.setFarmId(harvestEvent.getFarmId());
        existingEvent.setBlockId(harvestEvent.getBlockId());
        existingEvent.setHarvestQuantityKg(harvestEvent.getHarvestQuantityKg());
        existingEvent.setQualityGrade(harvestEvent.getQualityGrade());
        existingEvent.setQualityGradeDescription(harvestEvent.getQualityGradeDescription());
        existingEvent.setHarvestTeamId(harvestEvent.getHarvestTeamId());
        existingEvent.setHarvestSupervisor(harvestEvent.getHarvestSupervisor());
        existingEvent.setWeatherConditions(harvestEvent.getWeatherConditions());
        existingEvent.setStorageLocation(harvestEvent.getStorageLocation());
        
        return harvestEventRepository.save(existingEvent);
    }

    @Override
    public void deleteHarvestEvent(String harvestId) {
        if (!harvestEventRepository.existsById(harvestId)) {
            throw new IllegalArgumentException("Harvest event not found with ID: " + harvestId);
        }
        harvestEventRepository.deleteById(harvestId);
    }

    @Override
    @Transactional(readOnly = true)
    public HarvestEvent getHarvestEventById(String harvestId) {
        return harvestEventRepository.findById(harvestId)
                .orElseThrow(() -> new IllegalArgumentException("Harvest event not found with ID: " + harvestId));
    }

    @Override
    @Transactional(readOnly = true)
    public HarvestEvent getHarvestEventByBatchId(String batchId) {
        // Business Rule: One harvest event creates exactly one batch
        return harvestEventRepository.findByBatchId(batchId)
                .orElseThrow(() -> new IllegalArgumentException("Harvest event not found for batch ID: " + batchId));
    }

    @Override
    @Transactional(readOnly = true)
    public List<HarvestEvent> getAllHarvestEvents() {
        return harvestEventRepository.findAll();
    }

    @Override
    @Transactional(readOnly = true)
    public List<HarvestEvent> getHarvestEventsByDateRange(LocalDate startDate, LocalDate endDate) {
        return harvestEventRepository.findByHarvestDateBetween(startDate, endDate);
    }

    @Override
    @Transactional(readOnly = true)
    public List<HarvestEvent> getHarvestEventsByVariety(MangoVariety variety) {
        return harvestEventRepository.findByMangoVariety(variety);
    }

    @Override
    @Transactional(readOnly = true)
    public List<HarvestEvent> getHarvestEventsByQualityGrade(QualityGrade grade) {
        return harvestEventRepository.findByQualityGrade(grade);
    }

    @Override
    @Transactional(readOnly = true)
    public List<HarvestEvent> getHarvestEventsByFarm(String farmId) {
        return harvestEventRepository.findByFarmId(farmId);
    }

    @Override
    @Transactional(readOnly = true)
    public List<HarvestEvent> getHarvestEventsByFarmAndDateRange(String farmId, LocalDate startDate, LocalDate endDate) {
        return harvestEventRepository.findByFarmAndDateRange(farmId, startDate, endDate);
    }

    @Override
    @Transactional(readOnly = true)
    public List<HarvestEvent> getHarvestEventsByVarietyAndGrade(MangoVariety variety, QualityGrade grade) {
        return harvestEventRepository.findByVarietyAndGrade(variety, grade);
    }

    @Override
    @Transactional(readOnly = true)
    public boolean batchIdExists(String batchId) {
        // Business Rule: batch_id must be unique
        return harvestEventRepository.existsByBatchId(batchId);
    }

    @Override
    @Transactional(readOnly = true)
    public Double getTotalHarvestQuantityByVariety(MangoVariety variety) {
        return harvestEventRepository.getTotalHarvestQuantityByVariety(variety);
    }

    @Override
    @Transactional(readOnly = true)
    public List<HarvestEvent> getHarvestEventsByTeam(String harvestTeamId) {
        return harvestEventRepository.findByHarvestTeamId(harvestTeamId);
    }

    @Override
    public HarvestEvent syncFromPlants(HarvestEvent harvestEvent) {
        // Business Rule: Batch ID generated by Plants system
        // Check if harvest event already exists for this batch
        if (harvestEvent.getBatchId() != null && batchIdExists(harvestEvent.getBatchId())) {
            // Update existing event
            HarvestEvent existingEvent = getHarvestEventByBatchId(harvestEvent.getBatchId());
            return updateHarvestEvent(existingEvent.getHarvestId(), harvestEvent);
        } else {
            // Create new event
            return createHarvestEvent(harvestEvent);
        }
    }
}