package com.sustainablefarm.service.impl;

import com.sustainablefarm.model.Batch;
import com.sustainablefarm.model.RawIntake;
import com.sustainablefarm.repository.BatchRepository;
import com.sustainablefarm.repository.RawIntakeRepository;
import com.sustainablefarm.service.RawIntakeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

/**
 * Service Implementation for RawIntake Entity
 * Raw material intake from Plants - Supporting Entity
 * 
 * Business Rules:
 * - One intake initializes exactly one batch
 * - Batch ID generated by Plants system
 * - Plants workstream integration
 * 
 * @author Abdoul Ben Fatao SANON
 * @version 1.0.0
 */
@Service
@Transactional
public class RawIntakeServiceImpl implements RawIntakeService {

    private final RawIntakeRepository rawIntakeRepository;
    private final BatchRepository batchRepository;

    @Autowired
    public RawIntakeServiceImpl(RawIntakeRepository rawIntakeRepository,
                              BatchRepository batchRepository) {
        this.rawIntakeRepository = rawIntakeRepository;
        this.batchRepository = batchRepository;
    }

    @Override
    public RawIntake createRawIntake(RawIntake rawIntake) {
        // Business Rule: Validate batch exists
        if (rawIntake.getBatch() != null) {
            Batch batch = batchRepository.findById(rawIntake.getBatch().getBatchId())
                    .orElseThrow(() -> new IllegalArgumentException("Batch not found"));
            
            // Business Rule: Validate batch is in appropriate status for intake
            if (batch.getCurrentStatus() != Batch.BatchStatus.CREATED && 
                batch.getCurrentStatus() != Batch.BatchStatus.INTAKE) {
                throw new IllegalArgumentException(
                    "Batch must be in CREATED or INTAKE status for raw intake. Current: " + batch.getCurrentStatus()
                );
            }
        }
        
        return rawIntakeRepository.save(rawIntake);
    }

    @Override
    public RawIntake updateRawIntake(String intakeId, RawIntake rawIntake) {
        RawIntake existingIntake = getRawIntakeById(intakeId);
        
        // Update fields
        existingIntake.setSourceFarm(rawIntake.getSourceFarm());
        existingIntake.setSourceBlock(rawIntake.getSourceBlock());
        existingIntake.setIntakeDate(rawIntake.getIntakeDate());
        existingIntake.setReceivedQuantityKg(rawIntake.getReceivedQuantityKg());
        existingIntake.setReceivedVariety(rawIntake.getReceivedVariety());
        existingIntake.setReceivedGrade(rawIntake.getReceivedGrade());
        existingIntake.setIntakeOperator(rawIntake.getIntakeOperator());
        
        return rawIntakeRepository.save(existingIntake);
    }

    @Override
    public void deleteRawIntake(String intakeId) {
        if (!rawIntakeRepository.existsById(intakeId)) {
            throw new IllegalArgumentException("Raw intake not found with ID: " + intakeId);
        }
        rawIntakeRepository.deleteById(intakeId);
    }

    @Override
    @Transactional(readOnly = true)
    public RawIntake getRawIntakeById(String intakeId) {
        return rawIntakeRepository.findById(intakeId)
                .orElseThrow(() -> new IllegalArgumentException("Raw intake not found with ID: " + intakeId));
    }

    @Override
    @Transactional(readOnly = true)
    public RawIntake getRawIntakeByBatchId(String batchId) {
        // Business Rule: One intake initializes exactly one batch
        return rawIntakeRepository.findByBatchBatchId(batchId)
                .orElseThrow(() -> new IllegalArgumentException("Raw intake not found for batch ID: " + batchId));
    }

    @Override
    @Transactional(readOnly = true)
    public List<RawIntake> getAllRawIntakes() {
        return rawIntakeRepository.findAll();
    }

    @Override
    @Transactional(readOnly = true)
    public List<RawIntake> getRawIntakesByDateRange(LocalDate startDate, LocalDate endDate) {
        return rawIntakeRepository.findByIntakeDateBetween(startDate, endDate);
    }

    @Override
    @Transactional(readOnly = true)
    public List<RawIntake> getRawIntakesBySourceFarm(String sourceFarm) {
        return rawIntakeRepository.findBySourceFarm(sourceFarm);
    }

    @Override
    @Transactional(readOnly = true)
    public List<RawIntake> getRawIntakesByVariety(com.sustainablefarm.model.HarvestEvent.MangoVariety variety) {
        return rawIntakeRepository.findByReceivedVariety(variety);
    }

    @Override
    @Transactional(readOnly = true)
    public List<RawIntake> getRawIntakesByGrade(com.sustainablefarm.model.HarvestEvent.QualityGrade grade) {
        return rawIntakeRepository.findByReceivedGrade(grade);
    }

    @Override
    @Transactional(readOnly = true)
    public List<RawIntake> getRawIntakesBySourceFarmAndDateRange(String farm, LocalDate startDate, LocalDate endDate) {
        return rawIntakeRepository.findBySourceFarmAndDateRange(farm, startDate, endDate);
    }

    @Override
    @Transactional(readOnly = true)
    public Double getTotalReceivedQuantityByVariety(com.sustainablefarm.model.HarvestEvent.MangoVariety variety) {
        return rawIntakeRepository.getTotalReceivedQuantityByVariety(variety);
    }

    @Override
    @Transactional(readOnly = true)
    public long countByReceivedGrade(com.sustainablefarm.model.HarvestEvent.QualityGrade grade) {
        return rawIntakeRepository.countByReceivedGrade(grade);
    }

    @Override
    public RawIntake initializeBatchFromIntake(String intakeId) {
        RawIntake intake = getRawIntakeById(intakeId);
        Batch batch = intake.getBatch();
        
        // Business Rule: One intake initializes exactly one batch
        // Update batch status to INTAKE
        batch.setCurrentStatus(Batch.BatchStatus.INTAKE);
        batchRepository.save(batch);
        
        return intake;
    }
}