-- Baseline schema for the Sustainable Farm visitor management module.
-- Uses "if not exists" so it can be applied idempotently on databases that
-- predate Flyway versioning (see spring.flyway.baseline-version=0).

create table if not exists agri_activity (
    active boolean not null,
    capacity integer not null check ((capacity>=1)),
    duration_minutes integer not null check ((duration_minutes>=1)),
    price numeric(12,2) not null,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    name varchar(150) not null,
    description varchar(1000),
    primary key (id)
);

create table if not exists time_slot (
    end_time time(0) not null,
    max_capacity integer not null check ((max_capacity>=1) and (max_capacity<=10)),
    slot_date date not null,
    start_time time(0) not null,
    created_at timestamp(6) with time zone not null,
    guide_id bigint,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    status varchar(20) not null check ((status in ('AVAILABLE','RESERVED','FULL','CANCELLED','COMPLETED'))),
    primary key (id)
);

create table if not exists visitor (
    group_size integer not null check ((group_size>=1)),
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    visitor_type varchar(20) not null check ((visitor_type in ('INDIVIDUAL','GROUP','SCHOOL','PARTNER'))),
    phone varchar(30),
    language varchar(40),
    full_name varchar(150) not null,
    email varchar(200),
    special_needs varchar(500),
    primary key (id)
);

create table if not exists registration (
    is_prospect boolean not null,
    created_at timestamp(6) with time zone not null,
    event_id bigint,
    id bigint generated by default as identity,
    time_slot_id bigint,
    updated_at timestamp(6) with time zone not null,
    visitor_id bigint not null,
    status varchar(20) not null check ((status in ('PENDING','CONFIRMED','CHECKED_IN','REJECTED','CANCELLED'))),
    visit_purpose varchar(20) not null check ((visit_purpose in ('TOURISM','PURCHASE','PARTNERSHIP','INVESTMENT','EDUCATION','OTHER'))),
    primary key (id),
    constraint uk_registration_visitor_timeslot unique (visitor_id, time_slot_id),
    constraint uk_registration_event_visitor unique (event_id, visitor_id),
    constraint fk_registration_time_slot foreign key (time_slot_id) references time_slot,
    constraint fk_registration_visitor foreign key (visitor_id) references visitor
);

create table if not exists briefing (
    created_at timestamp(6) with time zone not null,
    delivered_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    registration_id bigint not null unique,
    updated_at timestamp(6) with time zone not null,
    status varchar(20) not null check ((status in ('DONE','PENDING','NOT_DONE'))),
    staff_member varchar(150),
    signature varchar(500),
    primary key (id),
    constraint fk_briefing_registration foreign key (registration_id) references registration
);

create table if not exists booking (
    people_count integer not null check ((people_count>=1)),
    total_amount numeric(12,2) not null,
    agri_activity_id bigint not null,
    confirmation_sent_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    reminder_scheduled_at timestamp(6) with time zone,
    reminder_sent_at timestamp(6) with time zone,
    time_slot_id bigint not null,
    updated_at timestamp(6) with time zone not null,
    payment_method varchar(20) check ((payment_method in ('CASH','ORANGE_MONEY','MOOV_MONEY'))),
    payment_status varchar(20) not null check ((payment_status in ('UNPAID','PAID','REFUNDED'))),
    status varchar(20) not null check ((status in ('PENDING','CONFIRMED','COMPLETED','CANCELLED'))),
    visitor_phone varchar(30),
    visitor_full_name varchar(150) not null,
    visitor_email varchar(255) not null,
    primary key (id),
    constraint fk_booking_activity foreign key (agri_activity_id) references agri_activity,
    constraint fk_booking_time_slot foreign key (time_slot_id) references time_slot
);

create table if not exists event (
    max_capacity integer not null check ((max_capacity>=1)),
    created_at timestamp(6) with time zone not null,
    end_date_time timestamp(6) not null,
    id bigint generated by default as identity,
    start_date_time timestamp(6) not null,
    updated_at timestamp(6) with time zone not null,
    status varchar(20) not null check ((status in ('DRAFT','PUBLISHED','CANCELLED','COMPLETED'))),
    event_type varchar(30) not null check ((event_type in ('OPEN_DAY','PARTNER_BUYER','SCHOOL','COMMUNITY','OTHER'))),
    location varchar(150),
    title varchar(150) not null,
    description varchar(1000),
    primary key (id)
);

create table if not exists tour_stop (
    active boolean not null,
    duration_minutes integer not null check ((duration_minutes>=1)),
    max_capacity integer check ((max_capacity>=1)),
    position integer not null check ((position>=1)),
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    location varchar(150),
    name varchar(150) not null,
    demo varchar(1000),
    safety_notes varchar(1000),
    description varchar(2000),
    primary key (id)
);

create table if not exists workshop (
    duration_minutes integer not null check ((duration_minutes>=1)),
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    status varchar(20) not null check ((status in ('DRAFT','ACTIVE','INACTIVE'))),
    target_group varchar(60) not null,
    facilitator varchar(100),
    name varchar(150) not null,
    description varchar(1000),
    primary key (id)
);

create table if not exists survey_send (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    sent_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    visitor_id bigint not null,
    channel varchar(20) not null check ((channel in ('ON_SITE','EMAIL','SMS','WHATSAPP'))),
    status varchar(20) not null check ((status in ('SENT','RECEIVED'))),
    message_template varchar(500),
    primary key (id),
    constraint fk_survey_send_visitor foreign key (visitor_id) references visitor
);

create table if not exists feedback (
    rating integer not null check ((rating<=5) and (rating>=1)),
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    submitted_at timestamp(6) with time zone not null,
    survey_send_id bigint unique,
    updated_at timestamp(6) with time zone not null,
    visitor_id bigint not null,
    origin varchar(20) not null check ((origin in ('ON_SITE','EMAIL','SMS','WHATSAPP'))),
    routed_to varchar(60),
    briefing_clear varchar(1000),
    comment varchar(1000),
    educational_value varchar(1000),
    recommend varchar(1000),
    primary key (id),
    constraint fk_feedback_survey_send foreign key (survey_send_id) references survey_send,
    constraint fk_feedback_visitor foreign key (visitor_id) references visitor
);
