-- A5: staff / guides table and FK from time_slot.guide_id.
-- Idempotent so it applies cleanly on databases that already ran this
-- migration or that predate Flyway versioning.

create table if not exists staff (
    is_active boolean not null,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    full_name varchar(150) not null,
    email varchar(200),
    phone varchar(30),
    role varchar(20) not null check ((role in ('GUIDE','RECEPTION','FARM','MANAGER'))),
    primary key (id)
);

-- Only add the FK when no orphan guide_id values exist in time_slot;
-- legacy rows that reference unknown staff keep the raw column value.
do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'fk_time_slot_guide'
    ) and not exists (
        select 1 from time_slot t
        left join staff s on s.id = t.guide_id
        where t.guide_id is not null and s.id is null
    ) then
        alter table time_slot
            add constraint fk_time_slot_guide foreign key (guide_id) references staff;
    end if;
end $$;