package com.sustainablefarm.service;

import com.sustainablefarm.model.HarvestEvent;
import com.sustainablefarm.model.HarvestEvent.MangoVariety;
import com.sustainablefarm.model.HarvestEvent.QualityGrade;

import java.time.LocalDate;
import java.util.List;

/**
 * Service Interface for HarvestEvent Entity
 * Harvest data from Plants workstream - Integration Entity
 * 
 * @author Abdoul Ben Fatao SANON
 * @version 1.0.0
 */
public interface HarvestEventService {

    /**
     * Create new harvest event
     */
    HarvestEvent createHarvestEvent(HarvestEvent harvestEvent);

    /**
     * Update harvest event
     */
    HarvestEvent updateHarvestEvent(String harvestId, HarvestEvent harvestEvent);

    /**
     * Delete harvest event
     */
    void deleteHarvestEvent(String harvestId);

    /**
     * Get harvest event by ID
     */
    HarvestEvent getHarvestEventById(String harvestId);

    /**
     * Get harvest event by batch ID
     * Business Rule: One harvest event creates exactly one batch
     */
    HarvestEvent getHarvestEventByBatchId(String batchId);

    /**
     * Get all harvest events
     */
    List<HarvestEvent> getAllHarvestEvents();

    /**
     * Get harvest events by date range
     */
    List<HarvestEvent> getHarvestEventsByDateRange(LocalDate startDate, LocalDate endDate);

    /**
     * Get harvest events by mango variety
     */
    List<HarvestEvent> getHarvestEventsByVariety(MangoVariety variety);

    /**
     * Get harvest events by quality grade
     */
    List<HarvestEvent> getHarvestEventsByQualityGrade(QualityGrade grade);

    /**
     * Get harvest events by farm
     */
    List<HarvestEvent> getHarvestEventsByFarm(String farmId);

    /**
     * Get harvest events by farm and date range
     */
    List<HarvestEvent> getHarvestEventsByFarmAndDateRange(String farmId, LocalDate startDate, LocalDate endDate);

    /**
     * Get harvest events by variety and quality grade
     */
    List<HarvestEvent> getHarvestEventsByVarietyAndGrade(MangoVariety variety, QualityGrade grade);

    /**
     * Check if batch ID already exists
     * Business Rule: batch_id must be unique
     */
    boolean batchIdExists(String batchId);

    /**
     * Get total harvest quantity by variety
     */
    Double getTotalHarvestQuantityByVariety(MangoVariety variety);

    /**
     * Get harvest events by team
     */
    List<HarvestEvent> getHarvestEventsByTeam(String harvestTeamId);

    /**
     * Sync harvest event from Plants workstream
     * Business Rule: Batch ID generated by Plants system
     */
    HarvestEvent syncFromPlants(HarvestEvent harvestEvent);
}