package com.sustainablefarm.modules.producttransformation.resources.harvestevent.model;
import com.sustainablefarm.modules.producttransformation.resources.batch.model.Batch;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import java.time.LocalDate;
import java.time.LocalTime;
import java.math.BigDecimal;

/**
 * HarvestEvent Entity
 * Harvest data from Plants workstream - Integration Entity
 * 
 * Business Rule: Batch ID generated by Plants system
 * Business Rule: One harvest event creates exactly one batch
 * 
 * Architecture Note: 
 * - batch_id is stored as VARCHAR without explicit database FK constraint
 * - This is intentional for Plants workstream integration
 * - Relationship to Batch is maintained through batch_id field value
 * - Per MCD: "HARVEST_EVENT '1' -- '1' BATCH : creates_batch"
 * 
 * @author Abdoul Ben Fatao SANON
 * @version 1.0.0
 */
@Entity
@Table(name = "harvest_event")
@Getter
@Setter
@EqualsAndHashCode
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class HarvestEvent {

    @Id
    @Column(name = "harvest_id", length = 50)
    private String harvestId;

    @Column(name = "batch_id", nullable = false, unique = true, length = 50)
    private String batchId;

    // Note: No @OneToOne relationship to Batch entity
    // Reason: Database schema has batch_id as VARCHAR foreign key without explicit FK constraint
    // Relationship is maintained through batch_id field for Plants integration
    // Per MCD: "HARVEST_EVENT '1' -- '1' BATCH : creates_batch"

    @Column(name = "harvest_date", nullable = false)
    private LocalDate harvestDate;

    @Column(name = "harvest_time")
    private LocalTime harvestTime;

    @Enumerated(EnumType.STRING)
    @Column(name = "mango_variety", nullable = false, length = 20)
    private MangoVariety mangoVariety;

    @Column(name = "farm_id", nullable = false, length = 50)
    private String farmId;

    @Column(name = "block_id", nullable = false, length = 50)
    private String blockId;

    @Column(name = "harvest_quantity_kg", nullable = false, precision = 10, scale = 2)
    private BigDecimal harvestQuantityKg;

    @Enumerated(EnumType.STRING)
    @Column(name = "quality_grade", nullable = false, length = 1)
    private QualityGrade qualityGrade;

    @Column(name = "quality_grade_description", length = 200)
    private String qualityGradeDescription;

    @Column(name = "harvest_team_id", length = 50)
    private String harvestTeamId;

    @Column(name = "harvest_supervisor", length = 100)
    private String harvestSupervisor;

    @Column(name = "weather_conditions", length = 200)
    private String weatherConditions;

    @Column(name = "storage_location", length = 50)
    private String storageLocation;

    @Column(name = "created_at", updatable = false)
    private java.sql.Timestamp createdAt;

    @Column(name = "updated_at")
    private java.sql.Timestamp updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = new java.sql.Timestamp(System.currentTimeMillis());
        updatedAt = new java.sql.Timestamp(System.currentTimeMillis());
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = new java.sql.Timestamp(System.currentTimeMillis());
    }

    /**
     * Mango Variety Enum
     * Business Rule: Matches database CHECK constraint
     */
    public enum MangoVariety {
        KEITT,
        KENT,
        TOMMY,
        AMÉLIE,
        OTHER
    }

    /**
     * Quality Grade Enum
     * Business Rule: Matches database CHECK constraint
     */
    public enum QualityGrade {
        A,    // Premium - No defects
        B,    // Standard - Minor defects
        C,    // Processing - Visible defects
        D     // Reject - Significant defects
    }
}